services:
  backend:
    build: .
    container_name: fastapi-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - postgres_host=db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${postgres_password}
      POSTGRES_DB: ${postgres_db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${postgres_user} -d ${postgres_db}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    ports:
      - "5432:5432"
    networks:
      - backend


volumes:
  pgdata:

networks:
  backend:
    driver: bridge